// Supplementary data for Birth Lottery
// Sources:
//   maternalMortality: World Bank ~2020 (decessi materni ogni 100.000 nati vivi)
//   womenInParliament: World Bank ~2023 (% seggi parlamentari femminili)
//   expectedSchooling: UNDP Human Development Report 2023 (anni di scuola attesi)
//   null = dato non disponibile

window.BIRTH_LOTTERY_EXTRA = {
  IND: { maternalMortality: 103,  womenInParliament: 13.2, expectedSchooling: 12.6 },
  CHN: { maternalMortality: 16,   womenInParliament: 26.4, expectedSchooling: 14.0 },
  NGA: { maternalMortality: 1047, womenInParliament: 4.3,  expectedSchooling: 10.3 },
  PAK: { maternalMortality: 154,  womenInParliament: 20.0, expectedSchooling: 8.5  },
  COD: { maternalMortality: 547,  womenInParliament: 12.7, expectedSchooling: 10.2 },
  ETH: { maternalMortality: 267,  womenInParliament: 41.0, expectedSchooling: 9.4  },
  BGD: { maternalMortality: 123,  womenInParliament: 21.0, expectedSchooling: 12.2 },
  USA: { maternalMortality: 23,   womenInParliament: 29.4, expectedSchooling: 16.3 },
  IDN: { maternalMortality: 173,  womenInParliament: 22.1, expectedSchooling: 13.6 },
  TZA: { maternalMortality: 238,  womenInParliament: 37.2, expectedSchooling: 9.5  },
  UGA: { maternalMortality: 284,  womenInParliament: 34.9, expectedSchooling: 10.9 },
  MOZ: { maternalMortality: 289,  womenInParliament: 43.2, expectedSchooling: 9.8  },
  NER: { maternalMortality: 441,  womenInParliament: 17.9, expectedSchooling: 6.9  },
  AGO: { maternalMortality: 222,  womenInParliament: 32.4, expectedSchooling: 11.3 },
  MLI: { maternalMortality: 354,  womenInParliament: 28.2, expectedSchooling: 7.5  },
  KEN: { maternalMortality: 530,  womenInParliament: 23.3, expectedSchooling: 11.0 },
  BRA: { maternalMortality: 72,   womenInParliament: 17.7, expectedSchooling: 15.8 },
  ZMB: { maternalMortality: 213,  womenInParliament: 15.9, expectedSchooling: 10.8 },
  TCD: { maternalMortality: 1063, womenInParliament: 26.5, expectedSchooling: 7.3  },
  CMR: { maternalMortality: 443,  womenInParliament: 33.0, expectedSchooling: 10.6 },
  SDN: { maternalMortality: 270,  womenInParliament: 30.5, expectedSchooling: 8.2  },
  BFA: { maternalMortality: 264,  womenInParliament: 9.5,  expectedSchooling: 8.4  },
  SSD: { maternalMortality: 1223, womenInParliament: 28.5, expectedSchooling: 5.5  },
  MWI: { maternalMortality: 381,  womenInParliament: 22.9, expectedSchooling: 11.1 },
  GIN: { maternalMortality: 553,  womenInParliament: 26.0, expectedSchooling: 9.4  },
  AFG: { maternalMortality: 620,  womenInParliament: null, expectedSchooling: 10.1 },
  PHL: { maternalMortality: 78,   womenInParliament: 28.6, expectedSchooling: 13.1 },
  VNM: { maternalMortality: 62,   womenInParliament: 30.3, expectedSchooling: 12.3 },
  SLE: { maternalMortality: 443,  womenInParliament: 12.3, expectedSchooling: 10.2 },
  SOM: { maternalMortality: 621,  womenInParliament: 26.2, expectedSchooling: 5.0  },
  MDG: { maternalMortality: 392,  womenInParliament: 28.0, expectedSchooling: 10.3 },
  ZWE: { maternalMortality: 357,  womenInParliament: 33.4, expectedSchooling: 12.1 },
  CIV: { maternalMortality: 480,  womenInParliament: 13.5, expectedSchooling: 9.5  },
  RWA: { maternalMortality: 259,  womenInParliament: 61.3, expectedSchooling: 11.1 },
  GHA: { maternalMortality: 263,  womenInParliament: 14.5, expectedSchooling: 12.7 },
  SEN: { maternalMortality: 261,  womenInParliament: 43.8, expectedSchooling: 9.5  },
  ZAF: { maternalMortality: 127,  womenInParliament: 46.7, expectedSchooling: 13.3 },
  MEX: { maternalMortality: 59,   womenInParliament: 49.6, expectedSchooling: 15.1 },
  EGY: { maternalMortality: 17,   womenInParliament: 28.1, expectedSchooling: 14.1 },
  MMR: { maternalMortality: 179,  womenInParliament: null, expectedSchooling: 10.8 },
  IRQ: { maternalMortality: 79,   womenInParliament: 29.3, expectedSchooling: 11.7 },
  YEM: { maternalMortality: 164,  womenInParliament: 0.5,  expectedSchooling: 8.5  },
  TGO: { maternalMortality: 391,  womenInParliament: 20.7, expectedSchooling: 11.2 },
  GTM: { maternalMortality: 96,   womenInParliament: 22.6, expectedSchooling: 11.4 },
  TUR: { maternalMortality: 17,   womenInParliament: 17.8, expectedSchooling: 18.0 },
  SAU: { maternalMortality: 17,   womenInParliament: 19.9, expectedSchooling: 16.5 },
  DZA: { maternalMortality: 78,   womenInParliament: 7.7,  expectedSchooling: 14.4 },
  IRN: { maternalMortality: 22,   womenInParliament: 6.0,  expectedSchooling: 15.1 },
  COL: { maternalMortality: 75,   womenInParliament: 31.4, expectedSchooling: 14.7 },
  ARG: { maternalMortality: 39,   womenInParliament: 46.2, expectedSchooling: 18.4 },
  VEN: { maternalMortality: 259,  womenInParliament: 22.2, expectedSchooling: 13.6 },
  PER: { maternalMortality: 69,   womenInParliament: 39.5, expectedSchooling: 15.0 },
  MYS: { maternalMortality: 29,   womenInParliament: 13.0, expectedSchooling: 13.8 },
  KHM: { maternalMortality: 152,  womenInParliament: 13.8, expectedSchooling: 11.1 },
  BOL: { maternalMortality: 155,  womenInParliament: 46.2, expectedSchooling: 14.2 },
  DEU: { maternalMortality: 4,    womenInParliament: 35.0, expectedSchooling: 17.0 },
  GBR: { maternalMortality: 10,   womenInParliament: 35.0, expectedSchooling: 17.4 },
  FRA: { maternalMortality: 8,    womenInParliament: 37.8, expectedSchooling: 15.8 },
  ESP: { maternalMortality: 4,    womenInParliament: 47.4, expectedSchooling: 17.8 },
  POL: { maternalMortality: 2,    womenInParliament: 28.7, expectedSchooling: 16.3 },
  UKR: { maternalMortality: 19,   womenInParliament: 20.8, expectedSchooling: 15.1 },
  RUS: { maternalMortality: 17,   womenInParliament: 17.1, expectedSchooling: 15.0 },
  JPN: { maternalMortality: 4,    womenInParliament: 9.7,  expectedSchooling: 15.2 },
  KOR: { maternalMortality: 8,    womenInParliament: 19.1, expectedSchooling: 16.5 },
  CAN: { maternalMortality: 11,   womenInParliament: 30.7, expectedSchooling: 16.4 },
  AUS: { maternalMortality: 3,    womenInParliament: 38.2, expectedSchooling: 21.1 },
  MAR: { maternalMortality: 72,   womenInParliament: 24.3, expectedSchooling: 13.3 },
  HTI: { maternalMortality: 480,  womenInParliament: 3.5,  expectedSchooling: 9.7  },
  HND: { maternalMortality: 72,   womenInParliament: 27.0, expectedSchooling: 12.1 },
  NIC: { maternalMortality: 78,   womenInParliament: 54.1, expectedSchooling: 12.5 },
  ITA: { maternalMortality: 5,    womenInParliament: 35.0, expectedSchooling: 16.0 },
};
